### ISSUE TITLE
OSError: exception: access violation writing 0x00000000

### ISSUE THREAD

**Issue by cberk** [AndreMiras/pycaw#19]
When attempting to change the master volume repeatedly, sometimes get one of two [errors] as sen below:

(
![Capture](https://user-images.githubusercontent.com/56160692/66209965-8e725180-e6b0-11e9-9496-162c268e993b.PNG)
![Capture2](https://user-images.githubusercontent.com/56160692/66209967-8fa37e80-e6b0-11e9-9ece-a56d05b98974.PNG)

- current requirements pycaw==20181226
- OS version - Windows 10 64 bit
- architecture
- Python version - 3.7.4

**Comment by cberk** [comment]
i am finding this tricky to catch as the errors don't appear in my console - they just terminate the process. 
When debugging, the errors appear but only terminate the process after running some additional (arbitrary) lines of code.

**Comment by lucatatas** [comment]
Were you able to solve this problem? I am having trouble as well...

**Comment by TurboAnonym** [comment]
Maybe it you changed the volume too fast and COM cant handle it (just a guess...). A delay could help.

**Comment by cberk** [comment]
> Were you able to solve this problem? I am having trouble as well...

I don't think I did, sorry :-(

**Comment by mrob95** [comment]
I was also running into this. As far as I can tell it is a double-free caused by using ctypes `cast` instead of COM `QueryInterface` to get a pointer to a new interface. 

When you do this, Python has two objects referencing the COM object, but the COM object still only records a reference count of 1 because it doesn't know about the cast. The double free occurs if python deletes one of its references, calling `Release`, then COM deletes the object, then Python tries to delete its second reference and call `Release` again.

This can be reproduced reliably by updating `examples/audio_endpoint_volume_example.py` to call `main` in a loop:
```python
 if __name__ == "__main__":
-    main()
+    for i in range(100):
+        main()
```

Causing:
```
OSError: exception: access violation writing 0x0000000000000000
Exception ignored in: <function _compointer_base.__del__ at 0x000002BA3B2B98A0>
Traceback (most recent call last):
  File "C:\Users\Mike\Documents\GitHub\pycaw\.venv\Lib\site-packages\comtypes\__init__.py", line 956, in __del__
    self.Release()
  File "C:\Users\Mike\Documents\GitHub\pycaw\.venv\Lib\site-packages\comtypes\__init__.py", line 1211, in Release
    return self.__com_Release()
           ^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation writing 0x0000000000000000
volume.GetMute(): 0
Traceback (most recent call last):
  File "C:\Users\Mike\Documents\GitHub\pycaw\examples\audio_endpoint_volume_example.py", line 26, in <module>
    main()
  File "C:\Users\Mike\Documents\GitHub\pycaw\examples\audio_endpoint_volume_example.py", line 17, in main
    print("volume.GetMasterVolumeLevel(): %s" % volume.GetMasterVolumeLevel())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation writing 0x00007FFB54466CC8
```

The solution is to replace
```
volume = cast(interface, POINTER(IAudioEndpointVolume))
```
with
```
volume = interface.QueryInterface(IAudioEndpointVolume)
```

I'll make a PR to do this in all the examples.

**Comment by AndreMiras** [comment]
This was fixed by #74 and released in v20240210. The problem was that `ctypes.cast()` could lead to the COM object being released twice. Pycaw now uses `QueryInterface()` instead. Thanks to everyone who helped track this down.
