### ISSUE TITLE
COMError from '_ctypes

### ISSUE THREAD

**Issue by developer-pritam** [AndreMiras/pycaw#35]
![Uploading 16180625783387550668867739936342.jpg…]()

I am using linux mint I don't have much knowledge of python.

Please look into this.

**Comment by TurboAnonym** [comment]
pycaw is a wrapper around the **Core Audio Windows API.**
It wont work on Linux **only** Windows 7? and upwards.

**Comment by yashgaurav69** [comment]
Is there any library available for mac or linux?

**Comment by TurboAnonym** [comment]
I think on mac you can use applescript - but not for sure.

**Comment by shukla1582** [comment]
will pycaw work on win7. have installed pycaw and com types.

having this error while I run pycaw.


Traceback (most recent call last):
File "C:/HandTrackingProject/VolumeHandControl.py", line 7, in 
from comtypes import CLSCTX_ALL
File "C:\HandTrackingProject\lib\site-packages\comtypes_init_.py", line 375
except COMError, err:
^
SyntaxError: invalid syntax

**Comment by AndreMiras** [comment]
Pycaw wraps the Windows Core Audio API, so it only works on Windows and can't run on Linux Mint.
The earlier reply already identified the platform mismatch. The README now calls out Windows-only support explicitly.
Closing as not planned.
