### ISSUE TITLE
Can't install pycaw

### ISSUE THREAD

**Issue by Lizzit** [AndreMiras/pycaw#47]
pip freeze:
- absl-py==0.13.0
- attrs==21.2.0
- cycler==0.10.0
- flake8==3.9.2
- importlib-metadata==4.6.1
- isort==5.9.2
- kiwisolver==1.3.1
- matplotlib==3.4.2
- mccabe==0.6.1
- mediapipe==0.8.6
- numpy==1.21.0
- opencv-contrib-python==4.5.3.56
- opencv-python==4.5.3.56
- Pillow==8.3.1
- protobuf==3.17.3
- pycodestyle==2.7.0
- pyflakes==2.3.1
- pyparsing==2.4.7
- python-dateutil==2.8.1
- six==1.16.0
- typing-extensions==3.10.0.0
- zipp==3.5.0

- OS: Win 10
- System: x64
- Python version: Python 3.7.5

The error that i found trying to install pycaw is the following:

Collecting pycaw
  Using cached pycaw-20181226.tar.gz (5.7 kB)

    ERROR: Command errored out with exit status 1:
     command: 'I:\pythonProjects\FaceRecognition\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\eliar\\AppData\\Local\\Temp\\pip-install-2ikjcpi3\\pycaw_9d02e670650645d1b5c4473e08566842\\setup.py'"'"'; __file__='"'"'C:\\Users\\eliar\\AppData\\Local\\Temp\\pip-install-2ikjcpi3\\pycaw_9d02e670650645d1b5c4473e08566842\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\eliar\AppData\Local\Temp\pip-pip-egg-info-3izzyrpl'
         cwd: C:\Users\eliar\AppData\Local\Temp\pip-install-2ikjcpi3\pycaw_9d02e670650645d1b5c4473e08566842\
    Complete output (24 lines):
    Traceback (most recent call last):
      File "I:\pythonProjects\FaceRecognition\venv\lib\site-packages\pkg_resources\__init__.py", line 2851, in get_entry_map
        ep_map = self._ep_map
      File "I:\pythonProjects\FaceRecognition\venv\lib\site-packages\pkg_resources\__init__.py", line 2813, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\eliar\AppData\Local\Temp\pip-install-2ikjcpi3\pycaw_9d02e670650645d1b5c4473e08566842\setup.py", line 11, in <module>
        install_requires=['comtypes', 'enum34', 'psutil', 'future'])
      File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "I:\pythonProjects\FaceRecognition\venv\lib\site-packages\setuptools\dist.py", line 453, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "I:\pythonProjects\FaceRecognition\venv\lib\site-packages\pkg_resources\__init__.py", line 641, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "I:\pythonProjects\FaceRecognition\venv\lib\site-packages\pkg_resources\__init__.py", line 2854, in get_entry_map
        self._get_metadata('entry_points.txt'), self
      File "I:\pythonProjects\FaceRecognition\venv\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/68/b4/3c45faa728c743348fb8e8d1ff2b73576eb7bdc0a11016dd830ed130493d/pycaw-20181226.tar.gz#sha256=4efff8cc1dcc13f4fe476e73cbccde9582f9a058b7fe9182ff4e132c7d794e96 (from https://pypi.org/simple/pycaw/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pycaw (from versions: 20181226)
ERROR: No matching distribution found for pycaw

Can someone help me please?

**Comment by AndreMiras** [comment]
A few things has changed since that version, give it another try and feel free to re-open if it still fails
